services:
  # mongodb://localhost:27018 - 3T studio connection string
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db 
    networks:
      - stack

  metabase:
    image: metabase/metabase:v0.49.0
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./data/metabase:/metabase-data
    networks:
      - stack
    depends_on:
      - mongodb

networks:
  stack:
    driver: bridge

volumes:
  mongodb_data: 
